### ISSUE TITLE
how to unlock during ci/cd pipeline building docker image

### ISSUE THREAD

**Issue by Daxcor69** [AGWA/git-crypt#225]
Ok first off I love this product. Thank you.

I am on a steep learning curve but making head way.  I am using gitlab to store my repo, I have a pipeline that builds my docker image.  I can't for the life of me figure out how to edit the pipeline to unlock the files.. during the build.  Here is a template that I am using to build the image. Btw, I am using just the simple key file, for the key.  This is using the shared running on gitlab.  I am guessing I have to add something to the docker build line.  Thank you again for any help you can provide.

Brad

```
docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
      echo $CI_REGISTRY_IMAGE${tag}
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
```
